# Generated by Django 4.0.7 on 2022-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
